In [ ]:
import autompc as ampc

from autompc.benchmarks import CartpoleSwingupBenchmark

benchmark = CartpoleSwingupBenchmark()

system = benchmark.system
trajs = benchmark.gen_trajs(seed=100, n_trajs=200, traj_len=100)

from autompc.sysid import MLPDAD
modeldad = MLPDAD(system, n_hidden_layers=1, hidden_size_1=32, n_train_iters=30,
               nonlintype="relu", n_dad_iters=0)

modeldad.train(trajs)

In [ ]:
import matplotlib.pyplot as plt
from autompc.graphs.kstep_graph import KstepPredAccGraph

graph = KstepPredAccGraph(system, trajs, kmax=20, metric="rmse")
graph.add_model(modeldad, "DaD MLP")
graph.add_model(modeldad, "DaD2 MLP")

fig = plt.figure()
ax = fig.gca()
graph(fig, ax)
ax.set_title("Comparison of MLP models")
plt.show()

In [6]:
import numpy as np
import copy

def test(a):
    print(a)
    a = 2

def test2(a):
    print(a)
    a[0] = 1

for i in range(2):
    print(i)

b = 4
test(b)
print(b)

e = np.array([5,5,5,5])

c = np.array([0,1,2,3])
test2(c)
print(c)

#best = copy.deepcopy(c)
best = c
print(best)
print(c)
c = e
print(best)
print(c)

data = np.load('dadIter_2.npz')
print(data['loss'])

0
1
4
4
[0 1 2 3]
[1 1 2 3]
[1 1 2 3]
[1 1 2 3]
[1 1 2 3]
[5 5 5 5]
[6.78154300e+04 1.04825320e+11 8.46481555e+14 2.97434418e+23
 1.12556072e+27 1.67696437e+27]


In [ ]:
# from autompc.sysid import MLPDAD
# modeldad = MLPDAD(system, n_hidden_layers=1, hidden_size_1=32, n_train_iters=2,
#                nonlintype="relu", n_dad_iters=5)

# modeldad.train(trajs)